### ISSUE TITLE
Trying to get Bitcoin Whitepaper by browing to the /bitcoin.pdf path.

### ISSUE THREAD

**Issue by wksantiago** [Kukks/BTCPayServerPlugins#7]
Only getting "404 - PAGE NOT FOUND"

**Comment by ryenski** [comment]
Same here. Bitcoin Whitepaper 1.0.2 is installed, `/bitcoin.pdf` is 404.

**Comment by Goro2030** [comment]
Same here .... latest version of BTCPayServer.

**Comment by Goro2030** [comment]
@Kukks ?

**Comment by Kukks** [comment]
Fixed in latest version. Sorry for the delay

**Comment by Goro2030** [comment]
I just did an upgrade and it is still not working. Have you merged the fix already? @Kukks

**Comment by ryenski** [comment]
Works for me in 1.0.3

**Comment by Goro2030** [comment]
Oh yes, it works now. had to go into "Manage Plugins" and update it from there. Thanks!
